# Generated by Django 6.0.7 on 2026-07-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code, e.g. AU, US, GB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Abroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('overview_title', models.CharField(max_length=255)),
                ('overview_description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='abroad/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abroad', to='homesection.country')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='homesection.abroad')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='homesection.abroad')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisaInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visa_type', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('abroad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_information', to='homesection.abroad')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
