# Generated by Django 6.0.7 on 2026-07-16 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('general', 'General English'), ('special', 'Special English')], default='general', max_length=20)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Itels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('reading', models.CharField(blank=True, max_length=250)),
                ('writing', models.CharField(blank=True, max_length=250)),
                ('listening', models.CharField(blank=True, max_length=250)),
                ('speaking', models.CharField(blank=True, max_length=250)),
                ('exam_fee', models.CharField(blank=True, max_length=250)),
                ('fee_at_axis', models.CharField(blank=True, max_length=250)),
                ('class_duration', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='program.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
